# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19BWUyA9L3iLfQt4Ms8uSCtWmFjhDLb48
"""

!pip install PyPDF2

import PyPDF2
import warnings
warnings.filterwarnings("ignore",category=DeprecationWarning)

!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

downloaded = drive.CreateFile({'id':'1EjjxwtaxD3jmLnIEGua2IlXT1047-7Cd'}) # replace the id with id of file you want to access
downloaded.GetContentFile('kids.pdf')

open_filename = open('kids.pdf', 'rb')

ind_manifesto = PyPDF2.PdfFileReader(open_filename)

ind_manifesto.getDocumentInfo()

total_pages = ind_manifesto.numPages
total_pages

!pip install textract

import textract

count = 5
text  = ''

while(count < total_pages):
    mani_page  = ind_manifesto.getPage(count)
    count += 1
    text += mani_page.extractText()

text

if text != '':
    text = text
    
else:
    textract.process(open_filename, method='tesseract', encoding='utf-8', langauge='eng' )

!pip install autocorrect

text=" ".join(filter(lambda x:x[0]!='#', text.split()))

text

text = ''.join([i for i in text if not i.isdigit()])

text

word="_ KID NORMAL_th Pass_Andrea.indd // :"
text = text.replace(word, "")

text

text = text.replace("™", "'")
text

text = text.replace("˜", "fi")
text

!pip install autocorrect

from autocorrect import Speller
from nltk.tokenize import word_tokenize


def removal(text):
    spell  = Speller(lang='en')
    texts = spell(text)
    return ' '.join([w.lower() for w in word_tokenize(text)])

text = text.replace(" '", "'")
text

text = text.replace(" n'", "n'")
text

punctuations = "!()-[]{};:'\,<>./?@#$%^&*_~'"
for x in punctuations: 
  text = text.replace(x, "")

text

text = text.replace("˚", "l")
text